packages:
  # all packages in direct subdirs of packages/
  - "bau/**"
  - "bau-css/**"
  - "bau-router/**"
  - "bau-ui/**"
  - "bausaurus/**"
  - "bau-astro/**"

  # all packages in subdirs of components/
  - "examples/**/*"
